begin;

create table if not exists public.party_rooms (
  code        text primary key,
  host_id     uuid references auth.users(id) on delete set null,
  media_id    integer not null,
  media_type  text not null check (media_type in ('movie', 'tv')),
  media_title text not null,
  media_poster text,
  season      integer default null,
  episode     integer default null,
  created_at  timestamptz not null default now(),
  expires_at  timestamptz not null default (now() + interval '12 hours')
);

create table if not exists public.party_messages (
  id        bigint generated by default as identity primary key,
  room_code text not null references public.party_rooms(code) on delete cascade,
  user_id   uuid references auth.users(id) on delete set null,
  username  text not null,
  content   text not null,
  created_at timestamptz not null default now(),
  constraint party_messages_content_check check (char_length(trim(content)) between 1 and 500)
);

create index if not exists party_rooms_expires_idx on public.party_rooms (expires_at);
create index if not exists party_messages_room_idx on public.party_messages (room_code, created_at asc);

alter table public.party_rooms    enable row level security;
alter table public.party_messages enable row level security;

-- party_rooms policies
create policy "Anyone can view rooms"
  on public.party_rooms for select
  to anon, authenticated
  using (expires_at > now());

create policy "Authenticated users can create rooms"
  on public.party_rooms for insert
  to authenticated
  with check (host_id = auth.uid());

create policy "Host can delete their room"
  on public.party_rooms for delete
  to authenticated
  using (host_id = auth.uid());

-- party_messages policies
create policy "Anyone can view messages in a valid room"
  on public.party_messages for select
  to anon, authenticated
  using (
    exists (
      select 1 from public.party_rooms
      where code = room_code and expires_at > now()
    )
  );

create policy "Authenticated users can send messages"
  on public.party_messages for insert
  to authenticated
  with check (user_id = auth.uid());

-- Grant permissions
grant select on table public.party_rooms to anon;
grant select, insert, delete on table public.party_rooms to authenticated;
grant all privileges on table public.party_rooms to service_role;

grant select on table public.party_messages to anon;
grant select, insert on table public.party_messages to authenticated;
grant all privileges on table public.party_messages to service_role;

grant usage, select on sequence public.party_messages_id_seq to authenticated, service_role;

-- Enable Realtime for live chat and presence
alter publication supabase_realtime add table public.party_messages;
alter publication supabase_realtime add table public.party_rooms;

commit;
