begin;

alter table public.profiles
  add column if not exists is_admin boolean not null default false;

create table if not exists public.reward_accounts (
  user_id uuid primary key references auth.users(id) on delete cascade,
  points_balance integer not null default 0,
  total_points_earned integer not null default 0,
  total_points_spent integer not null default 0,
  referral_code text not null unique,
  referred_by uuid references auth.users(id) on delete set null,
  watch_minutes integer not null default 0,
  referral_count integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.ensure_reward_account(p_user_id uuid)
returns public.reward_accounts
language plpgsql
security definer
set search_path = public
as $$
declare
  v_code text;
  v_account public.reward_accounts;
begin
  select referral_code into v_code from public.reward_accounts where user_id = p_user_id;
  if v_code is null then
    v_code := 'R' || upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 10));
    insert into public.reward_accounts (user_id, referral_code)
    values (p_user_id, v_code)
    on conflict (user_id) do update set referral_code = excluded.referral_code
    returning * into v_account;
    return v_account;
  end if;

  select * into v_account from public.reward_accounts where user_id = p_user_id;
  return v_account;
end;
$$;

create or replace function public.increment_reward_account_balance(p_user_id uuid, p_points integer)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.reward_accounts (user_id, referral_code)
  values (p_user_id, 'R' || upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 10)))
  on conflict (user_id) do nothing;

  update public.reward_accounts
  set points_balance = points_balance + p_points,
      total_points_earned = total_points_earned + p_points,
      updated_at = now()
  where user_id = p_user_id;
end;
$$;

create or replace function public.increment_reward_account_spent(p_user_id uuid, p_points integer)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.reward_accounts
  set points_balance = greatest(points_balance - p_points, 0),
      total_points_spent = total_points_spent + p_points,
      updated_at = now()
  where user_id = p_user_id;
end;
$$;

create table if not exists public.reward_ledger (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  entry_type text not null,
  points integer not null,
  reference_id bigint,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.referrals (
  id bigint generated by default as identity primary key,
  referrer_id uuid not null references auth.users(id) on delete cascade,
  referred_id uuid not null references auth.users(id) on delete cascade unique,
  referral_code text not null,
  status text not null default 'pending' check (status in ('pending', 'verified', 'rewarded')),
  reward_points integer not null default 0,
  created_at timestamptz not null default now(),
  verified_at timestamptz,
  rewarded_at timestamptz
);

create table if not exists public.reward_requests (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  reward_type text not null default 'paypal_giftcard',
  requested_points integer not null check (requested_points > 0),
  requested_value_usd numeric(10,2) not null check (requested_value_usd > 0),
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected', 'fulfilled')),
  notes text,
  admin_notes text,
  payout_email text,
  payout_reference text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  reviewed_at timestamptz,
  reviewed_by uuid references auth.users(id) on delete set null,
  fulfilled_at timestamptz
);

create index if not exists reward_requests_status_idx on public.reward_requests (status, created_at desc);
create index if not exists reward_requests_user_idx on public.reward_requests (user_id, created_at desc);
create index if not exists reward_ledger_user_idx on public.reward_ledger (user_id, created_at desc);
create index if not exists referrals_referrer_idx on public.referrals (referrer_id, created_at desc);

alter table public.reward_accounts enable row level security;
alter table public.reward_ledger enable row level security;
alter table public.referrals enable row level security;
alter table public.reward_requests enable row level security;

create policy "Users can view their reward account"
  on public.reward_accounts for select
  to authenticated
  using (user_id = auth.uid());

create policy "Users can view their ledger"
  on public.reward_ledger for select
  to authenticated
  using (user_id = auth.uid());

create policy "Users can view their referrals"
  on public.referrals for select
  to authenticated
  using (referrer_id = auth.uid() or referred_id = auth.uid());

create policy "Users can view their requests"
  on public.reward_requests for select
  to authenticated
  using (user_id = auth.uid());

create policy "Users can insert their requests"
  on public.reward_requests for insert
  to authenticated
  with check (user_id = auth.uid());

create policy "Admins can manage reward requests"
  on public.reward_requests for all
  to authenticated
  using (
    exists (
      select 1 from public.profiles p
      where p.id = auth.uid() and p.is_admin = true
    )
  )
  with check (
    exists (
      select 1 from public.profiles p
      where p.id = auth.uid() and p.is_admin = true
    )
  );

create policy "Admins can manage reward accounts"
  on public.reward_accounts for all
  to authenticated
  using (
    exists (
      select 1 from public.profiles p
      where p.id = auth.uid() and p.is_admin = true
    )
  )
  with check (
    exists (
      select 1 from public.profiles p
      where p.id = auth.uid() and p.is_admin = true
    )
  );

create policy "Admins can manage reward ledger"
  on public.reward_ledger for all
  to authenticated
  using (
    exists (
      select 1 from public.profiles p
      where p.id = auth.uid() and p.is_admin = true
    )
  )
  with check (
    exists (
      select 1 from public.profiles p
      where p.id = auth.uid() and p.is_admin = true
    )
  );

create policy "Admins can manage referrals"
  on public.referrals for all
  to authenticated
  using (
    exists (
      select 1 from public.profiles p
      where p.id = auth.uid() and p.is_admin = true
    )
  )
  with check (
    exists (
      select 1 from public.profiles p
      where p.id = auth.uid() and p.is_admin = true
    )
  );

grant select, insert, update, delete on table public.reward_accounts to authenticated;
grant select, insert, update, delete on table public.reward_ledger to authenticated;
grant select, insert, update, delete on table public.referrals to authenticated;
grant select, insert, update, delete on table public.reward_requests to authenticated;
grant execute on function public.ensure_reward_account(uuid) to authenticated, service_role;
grant execute on function public.increment_reward_account_balance(uuid, integer) to authenticated, service_role;
grant execute on function public.increment_reward_account_spent(uuid, integer) to authenticated, service_role;
grant all privileges on table public.reward_accounts, public.reward_ledger, public.referrals, public.reward_requests to service_role;
grant usage, select on sequence public.reward_ledger_id_seq, public.referrals_id_seq, public.reward_requests_id_seq to authenticated, service_role;

commit;
