begin;

create table if not exists public.premium_codes (
  id bigint generated by default as identity primary key,
  code text not null,
  plan text not null check (plan in ('monthly', 'yearly')),
  duration_days integer not null check (duration_days between 1 and 3650),
  max_redemptions integer not null default 1 check (max_redemptions > 0),
  redemption_count integer not null default 0 check (redemption_count >= 0),
  active boolean not null default true,
  expires_at timestamp with time zone,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  created_by uuid references auth.users(id) on delete set null,
  last_redeemed_by uuid references auth.users(id) on delete set null,
  last_redeemed_at timestamp with time zone,
  constraint premium_codes_code_length_check check (char_length(trim(code)) between 4 and 128),
  constraint premium_codes_redemption_bounds_check check (redemption_count <= max_redemptions)
);

create unique index if not exists premium_codes_code_upper_key
  on public.premium_codes ((upper(trim(code))));

create index if not exists premium_codes_active_expires_idx
  on public.premium_codes (active, expires_at);

create table if not exists public.premium_code_redemptions (
  id bigint generated by default as identity primary key,
  code_id bigint not null references public.premium_codes(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  redeemed_at timestamp with time zone not null default now(),
  applied_plan text not null check (applied_plan in ('monthly', 'yearly')),
  applied_days integer not null check (applied_days between 1 and 3650),
  constraint premium_code_redemptions_unique_user_code unique (code_id, user_id)
);

create index if not exists premium_code_redemptions_user_idx
  on public.premium_code_redemptions (user_id, redeemed_at desc);

create index if not exists premium_code_redemptions_code_idx
  on public.premium_code_redemptions (code_id, redeemed_at desc);

alter table public.premium_codes enable row level security;
alter table public.premium_code_redemptions enable row level security;

grant all privileges on table public.premium_codes to service_role;
grant all privileges on table public.premium_code_redemptions to service_role;
grant usage, select on sequence public.premium_codes_id_seq to service_role;
grant usage, select on sequence public.premium_code_redemptions_id_seq to service_role;

create or replace function public.redeem_premium_code(p_code text, p_user_id uuid)
returns table (code_id bigint, plan text, duration_days integer)
language plpgsql
security definer
set search_path to 'public'
as $function$
declare
  matched_code public.premium_codes%rowtype;
begin
  if p_user_id is null then
    raise exception 'AUTH_REQUIRED';
  end if;

  if p_code is null or char_length(trim(p_code)) = 0 then
    raise exception 'INVALID_CODE';
  end if;

  select *
  into matched_code
  from public.premium_codes
  where upper(trim(code)) = upper(trim(p_code))
    and active = true
  for update;

  if not found then
    raise exception 'CODE_NOT_FOUND';
  end if;

  if matched_code.expires_at is not null and matched_code.expires_at <= now() then
    raise exception 'CODE_EXPIRED';
  end if;

  if exists (
    select 1
    from public.premium_code_redemptions
    where code_id = matched_code.id
      and user_id = p_user_id
  ) then
    raise exception 'CODE_ALREADY_REDEEMED';
  end if;

  if matched_code.redemption_count >= matched_code.max_redemptions then
    raise exception 'CODE_REDEMPTION_LIMIT_REACHED';
  end if;

  insert into public.premium_code_redemptions (code_id, user_id, applied_plan, applied_days)
  values (matched_code.id, p_user_id, matched_code.plan, matched_code.duration_days);

  update public.premium_codes
  set
    redemption_count = redemption_count + 1,
    last_redeemed_at = now(),
    last_redeemed_by = p_user_id,
    updated_at = now(),
    active = case
      when redemption_count + 1 >= max_redemptions then false
      else active
    end
  where id = matched_code.id;

  return query
  select matched_code.id, matched_code.plan, matched_code.duration_days;
end;
$function$;

revoke all on function public.redeem_premium_code(text, uuid) from public;
grant execute on function public.redeem_premium_code(text, uuid) to service_role;

commit;
